### ISSUE TITLE
ES Modules Example

### ISSUE THREAD

**Issue by gavinr** [gavinr-maps/esri-svelte-example#4]
In addition to the esri-loader example, in theory we will be able to use the JS API directly using ES Modules soon:
https://github.com/Esri/feedback-js-api-next/blob/master/ES_modules.md

This issue is to add (parallel branch?) or replace the current example with an example that uses the ES Modules version of the API.

**Comment by gavinr** [comment]
https://www.esri.com/arcgis-blog/products/js-api-arcgis/announcements/es-modules-are-coming-soon-in-the-arcgis-api-for-javascript/

**Comment by gavinr** [comment]
When using rollup with the es modules, the challenge is that the re-builds every time you save a file, it takes 5-15 seconds (see https://github.com/Esri/jsapi-resources/issues/327 for discussion). A good alternative (Credit @jwasilgeo) is to use the Vite template, choose "Svelte", and then `npm install @arcgis/core`. I've tried it out on the https://github.com/gavinr/stl-live-crime/pull/21 project, and seems to work well. I think if this method seems the best, we should switch the primary example in this repo to show how to use that method.

**Comment by jwasilgeo** [comment]
👏 glad to hear you evaluated Vite + Svelte + `@arcgis/core`, too, and it’s working out for you!

I have some questions/concerns about how to handle locally managed assets (jsapi, calcite-components, etc.) when building for production in Vite. Let’s talk and compare notes soon!
